[build]
  publish = "./dist"
  command = "npm run build"
  [build.environment]
    NODE_VERSION = "18"

[dev]
  publish = "dist/"
  targetPort = 3000

[functions]
  directory = "functions"
  node_bundler = "esbuild"
